spring.application.name=pentagon
server.port=8081
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/webdb
spring.datasource.username=webuser
spring.datasource.password=1234

logging.level.org.springframework=info
logging.level.com.example=debug
logging.level.org.springframework.security=DEBUG

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# Toss Payments ??
toss.payments.client-key=test_ck_Poxy1XQL8RxGqE7nRjLLV7nO5Wml
toss.payments.secret-key=test_sk_vZnjEJeQVxyBAx514YEzrPmOoBN0
toss.payments.success-url=http://localhost:8081/api/payments/toss/success
toss.payments.fail-url=http://localhost:8081/api/payments/toss/fail